# Generated by Django 2.2.3 on 2019-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fillup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('request_created_date', models.DateField(auto_now_add=True)),
                ('target_launch_date', models.DateField(default=None, null=True)),
                ('request_synopsis', models.TextField(blank=True, default='', null=True)),
                ('estimated_date', models.DateField(blank=True, default=None, null=True)),
                ('actual_live_date', models.DateField(blank=True, default=None, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('approval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=20)),
                ('ontime_status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('action', models.CharField(blank=True, choices=[('Live', 'Live'), ('Hold', 'Hold'), ('Stop', 'Stop')], default='', max_length=20, null=True)),
                ('uat_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
