# Generated by Django 2.2.3 on 2019-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infofill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='close',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
