# Generated by Django 2.2.3 on 2019-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infofill', '0003_fillup_close_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Existing Client Enhancement', 'Existing Client Enhancement'), ('New Client Onboarding', 'New Client Onboarding')], default=None, max_length=50, null=True),
        ),
    ]
